swipe:
  3: 
    left: 
      command: "i3-msg workspace next"
    right: 
      command: "i3-msg workspace prev"
  4:
    left: 
      command: "i3-msg workspace next"
    right: 
      command: "i3-msg workspace prev"

threshold:
  swipe: 0.6

interval:
  swipe: 0.8