# Sample config file

# The theme colours can be an rgb string of the form "255, 255, 255" or a string that references the colours from your terminal theme: Reset, Black, Red, Yellow, Yellow, Blue, Magenta, Cyan, Gray, DarkGray, LightRed, LightYellow, LightYellow, LightBlue, LightMagenta, LightCyan, White.
theme:
  active: Yellow
  banner: Yellow
  error_border: Red
  error_text: LightRed
  hint: Black
  hovered: Yellow
  inactive: White
  playbar_background: Black
  playbar_progress: Green
  playbar_text: Yellow
  selected: Green
  text: Black

behavior:
  seek_milliseconds: 10000
  volume_increment: 10
  # The lower the number the higher the "frames per second". You can decrease this number so that the audio visualisation is smoother but this can be expensive!
  tick_rate_milliseconds: 100
